/****************************************************************************
*   Generated by ACUITY 5.21.1_0702
*   Match ovxlib 1.1.30
*
*   Neural Network appliction network definition source file
****************************************************************************/
/*-------------------------------------------
                   Includes
 -------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>

#include "vsi_nn_pub.h"

#include "vnn_global.h"
#include "vnn_mnist.h"

/*-------------------------------------------
                   Macros
 -------------------------------------------*/

#define NEW_VXNODE(_node, _type, _in, _out, _uid) do {\
        _node = vsi_nn_AddNode( graph, _type, _in, _out, NULL );\
        if( NULL == _node ) {\
            goto error;\
        }\
        _node->uid = (uint32_t)_uid;\
    } while(0)

#define NEW_VIRTUAL_TENSOR(_id, _attr, _dtype) do {\
        memset( _attr.size, 0, VSI_NN_MAX_DIM_NUM * sizeof(uint32_t));\
        _attr.dim_num = VSI_NN_DIM_AUTO;\
        _attr.vtl = !VNN_APP_DEBUG;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set const tensor dims out of this macro.
#define NEW_CONST_TENSOR(_id, _attr, _dtype, _ofst, _size) do {\
        data = load_data( fp, _ofst, _size  );\
        _attr.vtl = FALSE;\
        _attr.is_const = TRUE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, data );\
        free( data );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set generic tensor dims out of this macro.
#define NEW_NORM_TENSOR(_id, _attr, _dtype) do {\
        _attr.vtl = FALSE;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensor( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

// Set generic tensor dims out of this macro.
#define NEW_NORM_TENSOR_FROM_HANDLE(_id, _attr, _dtype) do {\
        _attr.vtl = FALSE;\
        _attr.is_const = FALSE;\
        _attr.dtype.vx_type = _dtype;\
        _id = vsi_nn_AddTensorFromHandle( graph, VSI_NN_TENSOR_ID_AUTO,\
                & _attr, NULL );\
        if( VSI_NN_TENSOR_ID_NA == _id ) {\
            goto error;\
        }\
    } while(0)

#define NET_NODE_NUM            (15)
#define NET_NORM_TENSOR_NUM     (2)
#define NET_CONST_TENSOR_NUM    (12)
#define NET_VIRTUAL_TENSOR_NUM  (15)
#define NET_TOTAL_TENSOR_NUM    (NET_NORM_TENSOR_NUM + NET_CONST_TENSOR_NUM + NET_VIRTUAL_TENSOR_NUM)

/*-------------------------------------------
               Local Variables
 -------------------------------------------*/

/*-------------------------------------------
                  Functions
 -------------------------------------------*/
static uint8_t* load_data
    (
    FILE  * fp,
    size_t  ofst,
    size_t  sz
    )
{
    uint8_t* data;
    int32_t ret;
    data = NULL;
    if( NULL == fp )
    {
        return NULL;
    }

    ret = fseek(fp, ofst, SEEK_SET);
    if (ret != 0)
    {
        VSILOGE("blob seek failure.");
        return NULL;
    }

    data = (uint8_t*)malloc(sz);
    if (data == NULL)
    {
        VSILOGE("buffer malloc failure.");
        return NULL;
    }
    ret = fread(data, 1, sz, fp);
    return data;
} /* load_data() */

vsi_nn_graph_t * vnn_CreateMnist
    (
    const char * data_file_name,
    vsi_nn_context_t in_ctx,
    const vsi_nn_preprocess_map_element_t * pre_process_map,
    uint32_t pre_process_map_count,
    const vsi_nn_postprocess_map_element_t * post_process_map,
    uint32_t post_process_map_count
    )
{
    uint32_t                _infinity = VSI_NN_FLOAT32_INF;
    vsi_status              status;
    vsi_bool                release_ctx;
    vsi_nn_context_t        ctx;
    vsi_nn_graph_t *        graph;
    vsi_nn_node_t *         node[NET_NODE_NUM];
    vsi_nn_tensor_id_t      norm_tensor[NET_NORM_TENSOR_NUM];
    vsi_nn_tensor_id_t      const_tensor[NET_CONST_TENSOR_NUM];
    vsi_nn_tensor_attr_t    attr;
    FILE *                  fp;
    uint8_t *               data;
    uint32_t                i = 0;
    char *                  use_img_process_s;
    int32_t                 enable_pre_post_process = 0;
    vsi_bool                sort = FALSE;

    uint32_t   shape_1[] = { 800, -1 };




    (void)(_infinity);
    ctx = NULL;
    graph = NULL;
    status = VSI_FAILURE;
    memset( &attr, 0, sizeof( attr ) );

    fp = fopen( data_file_name, "rb" );
    if( NULL == fp )
    {
        VSILOGE( "Open file %s failed.", data_file_name );
        goto error;
    }

    if( NULL == in_ctx )
    {
        ctx = vsi_nn_CreateContext();
    }
    else
    {
        ctx = in_ctx;
    }

    use_img_process_s = getenv( "VSI_USE_IMAGE_PROCESS" );
    if( use_img_process_s )
    {
        enable_pre_post_process = atoi(use_img_process_s);
    }

    graph = vsi_nn_CreateGraph( ctx, NET_TOTAL_TENSOR_NUM, NET_NODE_NUM );
    if( NULL == graph )
    {
        VSILOGE( "Create graph fail." );
        goto error;
    }
    vsi_nn_SetGraphVersion( graph, VNN_VERSION_MAJOR, VNN_VERSION_MINOR, VNN_VERSION_PATCH );
    vsi_nn_SetGraphInputs( graph, NULL, 1 );
    vsi_nn_SetGraphOutputs( graph, NULL, 1 );

/*-----------------------------------------
  Register client ops
 -----------------------------------------*/


/*-----------------------------------------
  Node definitions
 -----------------------------------------*/

    /*-----------------------------------------
      lid       - Conv_Conv_0_15
      var       - node[0]
      name      - Conv_Conv_0
      operation - convolution
      input     - [28, 28, 3, 1]
      filter    - [5, 5, 3, 20]
      output    - [24, 24, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[0], VSI_NN_OP_CONV2D, 3, 1, 15);
    node[0]->nn_param.conv2d.ksize[0] = 5;
    node[0]->nn_param.conv2d.ksize[1] = 5;
    node[0]->nn_param.conv2d.weights = 20;
    node[0]->nn_param.conv2d.stride[0] = 1;
    node[0]->nn_param.conv2d.stride[1] = 1;
    node[0]->nn_param.conv2d.pad[0] = 0;
    node[0]->nn_param.conv2d.pad[1] = 0;
    node[0]->nn_param.conv2d.pad[2] = 0;
    node[0]->nn_param.conv2d.pad[3] = 0;
    node[0]->nn_param.conv2d.group = 1;
    node[0]->nn_param.conv2d.dilation[0] = 1;
    node[0]->nn_param.conv2d.dilation[1] = 1;
    node[0]->nn_param.conv2d.multiplier = 0;
    node[0]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[0]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[0]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_Relu_1_14
      var       - node[1]
      name      - Relu_Relu_1
      operation - relu
      input     - [24, 24, 20, 1]
      output    - [24, 24, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[1], VSI_NN_OP_RELU, 1, 1, 14);

    /*-----------------------------------------
      lid       - MaxPool_MaxPool_2_13
      var       - node[2]
      name      - MaxPool_MaxPool_2
      operation - pooling
      input     - [24, 24, 20, 1]
      output    - [12, 12, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[2], VSI_NN_OP_POOL, 1, 1, 13);
    node[2]->nn_param.pool.ksize[0] = 2;
    node[2]->nn_param.pool.ksize[1] = 2;
    node[2]->nn_param.pool.stride[0] = 2;
    node[2]->nn_param.pool.stride[1] = 2;
    node[2]->nn_param.pool.pad[0] = 0;
    node[2]->nn_param.pool.pad[1] = 0;
    node[2]->nn_param.pool.pad[2] = 0;
    node[2]->nn_param.pool.pad[3] = 0;
    node[2]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[2]->nn_param.pool.round_type = VSI_NN_ROUND_FLOOR;
    node[2]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Conv_Conv_3_12
      var       - node[3]
      name      - Conv_Conv_3
      operation - convolution
      input     - [12, 12, 20, 1]
      filter    - [5, 5, 20, 20]
      output    - [8, 8, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[3], VSI_NN_OP_CONV2D, 3, 1, 12);
    node[3]->nn_param.conv2d.ksize[0] = 5;
    node[3]->nn_param.conv2d.ksize[1] = 5;
    node[3]->nn_param.conv2d.weights = 20;
    node[3]->nn_param.conv2d.stride[0] = 1;
    node[3]->nn_param.conv2d.stride[1] = 1;
    node[3]->nn_param.conv2d.pad[0] = 0;
    node[3]->nn_param.conv2d.pad[1] = 0;
    node[3]->nn_param.conv2d.pad[2] = 0;
    node[3]->nn_param.conv2d.pad[3] = 0;
    node[3]->nn_param.conv2d.group = 1;
    node[3]->nn_param.conv2d.dilation[0] = 1;
    node[3]->nn_param.conv2d.dilation[1] = 1;
    node[3]->nn_param.conv2d.multiplier = 0;
    node[3]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[3]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[3]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_Relu_4_11
      var       - node[4]
      name      - Relu_Relu_4
      operation - relu
      input     - [8, 8, 20, 1]
      output    - [8, 8, 20, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[4], VSI_NN_OP_RELU, 1, 1, 11);

    /*-----------------------------------------
      lid       - Conv_Conv_5_10
      var       - node[5]
      name      - Conv_Conv_5
      operation - convolution
      input     - [8, 8, 20, 1]
      filter    - [1, 1, 20, 50]
      output    - [8, 8, 50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[5], VSI_NN_OP_CONV2D, 3, 1, 10);
    node[5]->nn_param.conv2d.ksize[0] = 1;
    node[5]->nn_param.conv2d.ksize[1] = 1;
    node[5]->nn_param.conv2d.weights = 50;
    node[5]->nn_param.conv2d.stride[0] = 1;
    node[5]->nn_param.conv2d.stride[1] = 1;
    node[5]->nn_param.conv2d.pad[0] = 0;
    node[5]->nn_param.conv2d.pad[1] = 0;
    node[5]->nn_param.conv2d.pad[2] = 0;
    node[5]->nn_param.conv2d.pad[3] = 0;
    node[5]->nn_param.conv2d.group = 1;
    node[5]->nn_param.conv2d.dilation[0] = 1;
    node[5]->nn_param.conv2d.dilation[1] = 1;
    node[5]->nn_param.conv2d.multiplier = 0;
    node[5]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[5]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[5]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_Relu_6_9
      var       - node[6]
      name      - Relu_Relu_6
      operation - relu
      input     - [8, 8, 50, 1]
      output    - [8, 8, 50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[6], VSI_NN_OP_RELU, 1, 1, 9);

    /*-----------------------------------------
      lid       - Conv_Conv_7_8
      var       - node[7]
      name      - Conv_Conv_7
      operation - convolution
      input     - [8, 8, 50, 1]
      filter    - [1, 1, 50, 50]
      output    - [8, 8, 50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[7], VSI_NN_OP_CONV2D, 3, 1, 8);
    node[7]->nn_param.conv2d.ksize[0] = 1;
    node[7]->nn_param.conv2d.ksize[1] = 1;
    node[7]->nn_param.conv2d.weights = 50;
    node[7]->nn_param.conv2d.stride[0] = 1;
    node[7]->nn_param.conv2d.stride[1] = 1;
    node[7]->nn_param.conv2d.pad[0] = 0;
    node[7]->nn_param.conv2d.pad[1] = 0;
    node[7]->nn_param.conv2d.pad[2] = 0;
    node[7]->nn_param.conv2d.pad[3] = 0;
    node[7]->nn_param.conv2d.group = 1;
    node[7]->nn_param.conv2d.dilation[0] = 1;
    node[7]->nn_param.conv2d.dilation[1] = 1;
    node[7]->nn_param.conv2d.multiplier = 0;
    node[7]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[7]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[7]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_Relu_8_7
      var       - node[8]
      name      - Relu_Relu_8
      operation - relu
      input     - [8, 8, 50, 1]
      output    - [8, 8, 50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[8], VSI_NN_OP_RELU, 1, 1, 7);

    /*-----------------------------------------
      lid       - MaxPool_MaxPool_9_6
      var       - node[9]
      name      - MaxPool_MaxPool_9
      operation - pooling
      input     - [8, 8, 50, 1]
      output    - [4, 4, 50, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[9], VSI_NN_OP_POOL, 1, 1, 6);
    node[9]->nn_param.pool.ksize[0] = 2;
    node[9]->nn_param.pool.ksize[1] = 2;
    node[9]->nn_param.pool.stride[0] = 2;
    node[9]->nn_param.pool.stride[1] = 2;
    node[9]->nn_param.pool.pad[0] = 0;
    node[9]->nn_param.pool.pad[1] = 0;
    node[9]->nn_param.pool.pad[2] = 0;
    node[9]->nn_param.pool.pad[3] = 0;
    node[9]->nn_param.pool.type = VX_CONVOLUTIONAL_NETWORK_POOLING_MAX;
    node[9]->nn_param.pool.round_type = VSI_NN_ROUND_FLOOR;
    node[9]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Reshape_Reshape_12_5
      var       - node[10]
      name      - Reshape_Reshape_12
      operation - reshape
      input     - [4, 4, 50, 1]
      output    - [800, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[10], VSI_NN_OP_RESHAPE, 1, 1, 5);
    node[10]->nn_param.reshape.size = shape_1;
    node[10]->nn_param.reshape.dim_num = 2;

    /*-----------------------------------------
      lid       - Gemm_Gemm_13_4
      var       - node[11]
      name      - Gemm_Gemm_13
      operation - fullconnect
      input     - [800, 1]
      filter    - [800, 500]
      output    - [500, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[11], VSI_NN_OP_FCL, 3, 1, 4);
    node[11]->nn_param.fcl.weights = 500;
    node[11]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[11]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[11]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - Relu_Relu_14_3
      var       - node[12]
      name      - Relu_Relu_14
      operation - relu
      input     - [500, 1]
      output    - [500, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[12], VSI_NN_OP_RELU, 1, 1, 3);

    /*-----------------------------------------
      lid       - Gemm_Gemm_15_2
      var       - node[13]
      name      - Gemm_Gemm_15
      operation - fullconnect
      input     - [500, 1]
      filter    - [500, 10]
      output    - [10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[13], VSI_NN_OP_FCL, 3, 1, 2);
    node[13]->nn_param.fcl.weights = 10;
    node[13]->vx_param.overflow_policy = VX_CONVERT_POLICY_SATURATE;
    node[13]->vx_param.rounding_policy = VX_ROUND_POLICY_TO_ZERO;
    node[13]->vx_param.down_scale_size_rounding = VX_CONVOLUTIONAL_NETWORK_DS_SIZE_ROUNDING_FLOOR;

    /*-----------------------------------------
      lid       - LogSoftmax_LogSoftmax_16_1
      var       - node[14]
      name      - LogSoftmax_LogSoftmax_16
      operation - log_softmax
      input     - [10, 1]
      output    - [10, 1]
    -----------------------------------------*/
    NEW_VXNODE(node[14], VSI_NN_OP_LOG_SOFTMAX, 1, 1, 1);
    node[14]->nn_param.log_softmax.betaValue = 1.0;
    node[14]->nn_param.log_softmax.axis = 0;


/*-----------------------------------------
  Tensor initialize
 -----------------------------------------*/
    attr.dtype.fmt = VSI_NN_DIM_FMT_NCHW;
    /* @attach_LogSoftmax_LogSoftmax_16/out0_0:out0 */
    attr.size[0] = 10;
    attr.size[1] = 1;
    attr.dim_num = 2;
    attr.dtype.scale = 0.08882390707731247;
    attr.dtype.zero_point = 255;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[0], attr, VSI_NN_TYPE_UINT8);

    /* @input_16:out0 */
    attr.size[0] = 28;
    attr.size[1] = 28;
    attr.size[2] = 3;
    attr.size[3] = 1;
    attr.dim_num = 4;
    attr.dtype.scale = 0.003921568859368563;
    attr.dtype.zero_point = 127;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_NORM_TENSOR(norm_tensor[1], attr, VSI_NN_TYPE_UINT8);



    /* @Conv_Conv_0_15:weight */
    attr.size[0] = 5;
    attr.size[1] = 5;
    attr.size[2] = 3;
    attr.size[3] = 20;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0023029593285173178;
    attr.dtype.zero_point = 120;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[0], attr, VSI_NN_TYPE_UINT8, 80, 1500);

    /* @Conv_Conv_0_15:bias */
    attr.size[0] = 20;
    attr.dim_num = 1;
    attr.dtype.scale = 9.031213587105849e-06;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[1], attr, VSI_NN_TYPE_INT32, 0, 80);

    /* @Conv_Conv_3_12:weight */
    attr.size[0] = 5;
    attr.size[1] = 5;
    attr.size[2] = 20;
    attr.size[3] = 20;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0016071491409093142;
    attr.dtype.zero_point = 101;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[2], attr, VSI_NN_TYPE_UINT8, 1660, 10000);

    /* @Conv_Conv_3_12:bias */
    attr.size[0] = 20;
    attr.dim_num = 1;
    attr.dtype.scale = 2.1804778641972998e-05;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[3], attr, VSI_NN_TYPE_INT32, 1580, 80);

    /* @Conv_Conv_5_10:weight */
    attr.size[0] = 1;
    attr.size[1] = 1;
    attr.size[2] = 20;
    attr.size[3] = 50;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0029885475523769855;
    attr.dtype.zero_point = 115;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[4], attr, VSI_NN_TYPE_UINT8, 11860, 1000);

    /* @Conv_Conv_5_10:bias */
    attr.size[0] = 50;
    attr.dim_num = 1;
    attr.dtype.scale = 0.00018919576376946745;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[5], attr, VSI_NN_TYPE_INT32, 11660, 200);

    /* @Conv_Conv_7_8:weight */
    attr.size[0] = 1;
    attr.size[1] = 1;
    attr.size[2] = 50;
    attr.size[3] = 50;
    attr.dim_num = 4;
    attr.dtype.scale = 0.0026615820825099945;
    attr.dtype.zero_point = 111;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[6], attr, VSI_NN_TYPE_UINT8, 13060, 2500);

    /* @Conv_Conv_7_8:bias */
    attr.size[0] = 50;
    attr.dim_num = 1;
    attr.dtype.scale = 0.00018698444243187007;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[7], attr, VSI_NN_TYPE_INT32, 12860, 200);

    /* @Gemm_Gemm_13_4:weight */
    attr.size[0] = 800;
    attr.size[1] = 500;
    attr.dim_num = 2;
    attr.dtype.scale = 0.0007482828223146498;
    attr.dtype.zero_point = 131;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[8], attr, VSI_NN_TYPE_UINT8, 17560, 400000);

    /* @Gemm_Gemm_13_4:bias */
    attr.size[0] = 500;
    attr.dim_num = 1;
    attr.dtype.scale = 5.047116482582211e-05;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[9], attr, VSI_NN_TYPE_INT32, 15560, 2000);

    /* @Gemm_Gemm_15_2:weight */
    attr.size[0] = 500;
    attr.size[1] = 10;
    attr.dim_num = 2;
    attr.dtype.scale = 0.0014474574709311128;
    attr.dtype.zero_point = 126;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[10], attr, VSI_NN_TYPE_UINT8, 417600, 5000);

    /* @Gemm_Gemm_15_2:bias */
    attr.size[0] = 10;
    attr.dim_num = 1;
    attr.dtype.scale = 5.3635451269544096e-05;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_CONST_TENSOR(const_tensor[11], attr, VSI_NN_TYPE_INT32, 417560, 40);



    /* @Conv_Conv_0_15:out0 */
    attr.dtype.scale = 0.013567364774644375;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[0]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_Relu_1_14:out0 */
    attr.dtype.scale = 0.013567364774644375;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[1]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @MaxPool_MaxPool_2_13:out0 */
    attr.dtype.scale = 0.013567364774644375;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[2]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Conv_Conv_3_12:out0 */
    attr.dtype.scale = 0.06330692768096924;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[3]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_Relu_4_11:out0 */
    attr.dtype.scale = 0.06330692768096924;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[4]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Conv_Conv_5_10:out0 */
    attr.dtype.scale = 0.07025311887264252;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[5]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_Relu_6_9:out0 */
    attr.dtype.scale = 0.07025311887264252;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[6]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Conv_Conv_7_8:out0 */
    attr.dtype.scale = 0.06744931638240814;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[7]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_Relu_8_7:out0 */
    attr.dtype.scale = 0.06744931638240814;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[8]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @MaxPool_MaxPool_9_6:out0 */
    attr.dtype.scale = 0.06744931638240814;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[9]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Reshape_Reshape_12_5:out0 */
    attr.dtype.scale = 0.06744931638240814;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[10]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Gemm_Gemm_13_4:out0 */
    attr.dtype.scale = 0.037054941058158875;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[11]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Relu_Relu_14_3:out0 */
    attr.dtype.scale = 0.037054941058158875;
    attr.dtype.zero_point = 0;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[12]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);

    /* @Gemm_Gemm_15_2:out0 */
    attr.dtype.scale = 0.08882389962673187;
    attr.dtype.zero_point = 69;
    attr.dtype.qnt_type = VSI_NN_QNT_TYPE_AFFINE_ASYMMETRIC;
    NEW_VIRTUAL_TENSOR(node[13]->output.tensors[0], attr, VSI_NN_TYPE_UINT8);



/*-----------------------------------------
  Connection initialize
 -----------------------------------------*/
    node[0]->input.tensors[0] = norm_tensor[1];
    node[14]->output.tensors[0] = norm_tensor[0];

    /* Conv_Conv_0_15 */
    node[0]->input.tensors[1] = const_tensor[0]; /* data_weight */
    node[0]->input.tensors[2] = const_tensor[1]; /* data_bias */

    /* Relu_Relu_1_14 */
    node[1]->input.tensors[0] = node[0]->output.tensors[0];

    /* MaxPool_MaxPool_2_13 */
    node[2]->input.tensors[0] = node[1]->output.tensors[0];

    /* Conv_Conv_3_12 */
    node[3]->input.tensors[0] = node[2]->output.tensors[0];
    node[3]->input.tensors[1] = const_tensor[2]; /* data_weight */
    node[3]->input.tensors[2] = const_tensor[3]; /* data_bias */

    /* Relu_Relu_4_11 */
    node[4]->input.tensors[0] = node[3]->output.tensors[0];

    /* Conv_Conv_5_10 */
    node[5]->input.tensors[0] = node[4]->output.tensors[0];
    node[5]->input.tensors[1] = const_tensor[4]; /* data_weight */
    node[5]->input.tensors[2] = const_tensor[5]; /* data_bias */

    /* Relu_Relu_6_9 */
    node[6]->input.tensors[0] = node[5]->output.tensors[0];

    /* Conv_Conv_7_8 */
    node[7]->input.tensors[0] = node[6]->output.tensors[0];
    node[7]->input.tensors[1] = const_tensor[6]; /* data_weight */
    node[7]->input.tensors[2] = const_tensor[7]; /* data_bias */

    /* Relu_Relu_8_7 */
    node[8]->input.tensors[0] = node[7]->output.tensors[0];

    /* MaxPool_MaxPool_9_6 */
    node[9]->input.tensors[0] = node[8]->output.tensors[0];

    /* Reshape_Reshape_12_5 */
    node[10]->input.tensors[0] = node[9]->output.tensors[0];

    /* Gemm_Gemm_13_4 */
    node[11]->input.tensors[0] = node[10]->output.tensors[0];
    node[11]->input.tensors[1] = const_tensor[8]; /* data_weight */
    node[11]->input.tensors[2] = const_tensor[9]; /* data_bias */

    /* Relu_Relu_14_3 */
    node[12]->input.tensors[0] = node[11]->output.tensors[0];

    /* Gemm_Gemm_15_2 */
    node[13]->input.tensors[0] = node[12]->output.tensors[0];
    node[13]->input.tensors[1] = const_tensor[10]; /* data_weight */
    node[13]->input.tensors[2] = const_tensor[11]; /* data_bias */

    /* LogSoftmax_LogSoftmax_16_1 */
    node[14]->input.tensors[0] = node[13]->output.tensors[0];


    graph->output.tensors[0] = norm_tensor[0];
    graph->input.tensors[0] = norm_tensor[1];


    if( enable_pre_post_process )
    {
        sort = TRUE;
        if( pre_process_map_count > 0 )
        {
            for( i = 0; i < pre_process_map_count; i++ )
            {
                status = vsi_nn_AddGraphPreProcess(graph, pre_process_map[i].graph_input_idx,
                                                   pre_process_map[i].preprocesses,
                                                   pre_process_map[i].preprocess_count);
                TEST_CHECK_STATUS( status, error );
            }
        }

        if( post_process_map_count > 0 )
        {
            for( i = 0; i < post_process_map_count; i++ )
            {
                 status = vsi_nn_AddGraphPostProcess(graph, post_process_map[i].graph_output_idx,
                                                     post_process_map[i].postprocesses,
                                                     post_process_map[i].postprocess_count);
                 TEST_CHECK_STATUS( status, error );
            }
        }
    }

    status = vsi_nn_SetupGraph( graph, sort );
    TEST_CHECK_STATUS( status, error );


    if( VSI_FAILURE == status )
    {
        goto error;
    }

    fclose( fp );

    return graph;

error:
    if( NULL != fp )
    {
        fclose( fp );
    }

    release_ctx = ( NULL == in_ctx );
    vsi_nn_DumpGraphToJson( graph );
    vnn_ReleaseMnist( graph, release_ctx );

    return NULL;
} /* vsi_nn_CreateMnist() */

void vnn_ReleaseMnist
    (
    vsi_nn_graph_t * graph,
    vsi_bool release_ctx
    )
{
    vsi_nn_context_t ctx;
    if( NULL != graph )
    {
        ctx = graph->ctx;
        vsi_nn_ReleaseGraph( &graph );

        /*-----------------------------------------
        Unregister client ops
        -----------------------------------------*/
        

        if( release_ctx )
        {
            vsi_nn_ReleaseContext( &ctx );
        }
    }
} /* vsi_nn_ReleaseMnist() */

